# Generated by Django 6.0.2 on 2026-04-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0007_alter_eventpost_posted_by_alter_jobpost_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpost',
            old_name='venue',
            new_name='location',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='event_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='organizer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
