# Generated by Django 6.0.2 on 2026-04-12 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0008_rename_venue_eventpost_location_eventpost_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('MALAYALAM', 'Malayalam'), ('ENGLISH', 'English'), ('BCOM', 'BCom'), ('HISTORY', 'History'), ('ECONOMICS', 'Economics'), ('ZOOLOGY', 'Zoology'), ('POLYMER_CHEMISTRY', 'Polymer Chemistry'), ('PLANT_SCIENCE', 'Plant Science'), ('MATHS', 'Maths'), ('PHYSICS', 'Physics'), ('STATISTICS', 'Statistics')], max_length=30)),
                ('is_hod', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
