# Generated by Django 6.0.2 on 2026-03-26 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0012_emailotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='hidden_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
