# Generated by Django 6.0.2 on 2026-04-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0014_job_delete_alumnipost'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
