# Generated by Django 6.0.2 on 2026-04-10 14:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0016_eventpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventPost',
            new_name='Event',
        ),
    ]
