# Generated by Django 6.0.2 on 2026-04-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0017_rename_eventpost_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('MALAYALAM', 'Malayalam'), ('ENGLISH', 'English'), ('BCOM', 'BCom'), ('HISTORY', 'History'), ('ECONOMICS', 'Economics'), ('ZOOLOGY', 'Zoology'), ('POLYMER_CHEMISTRY', 'Polymer Chemistry'), ('PLANT_SCIENCE', 'Plant Science'), ('MATHS', 'Maths'), ('PHYSICS', 'Physics'), ('STATISTICS', 'Statistics')], max_length=30, null=True),
        ),
    ]
