# Generated by Django 6.0.2 on 2026-04-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_module', '0018_alumniprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
